-- 1
SELECT CUSTOMER_NAME 
FROM CUSTOMER
WHERE CUSTOMER_NAME LIKE 'Ma%';

-- 2
SELECT SUM(QUANTITY),SUM(UNIT_PRICE*QUANTITY)
FROM CUSTOMER NATURAL JOIN `ORDER` NATURAL JOIN ORDER_ITEM NATURAL JOIN ITEM
GROUP BY `ORDER_ID`;

-- 3
SELECT ORDER_ID
FROM SHIPMENT NATURAL JOIN WAREHOUSE
WHERE WAREHOUSE_CITY = 'Arica';
-- 4
SELECT SUM(UNIT_PRICE*QUANTITY)
FROM SHIPMENT NATURAL JOIN WAREHOUSE NATURAL JOIN ORDER_ITEM NATURAL JOIN ITEM
WHERE WAREHOUSE_ID = 8;